# Generated by Django 3.1.3 on 2020-11-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0002_car_renter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at']},
        ),
    ]
