# Generated by Django 3.1.3 on 2020-11-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0003_auto_20201106_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
    ]
