# Generated by Django 3.1.3 on 2020-11-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name="User's language"),
        ),
    ]
