# Generated by Django 3.1.3 on 2020-11-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201104_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name="user's language"),
        ),
    ]
